language: php
php:
  - 7.0
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    repo: TomasPilar/docker-deployment
after_success:
  - chmod 600 id_dsa
  - mv id_dsa ~/.ssh/id_dsa
before_install:
  - openssl aes-256-cbc -K $encrypted_8d8eae9ad9ee_key -iv $encrypted_8d8eae9ad9ee_iv -in id_dsa.enc -out ~/.ssh/id_dsa -d
